version: "2"
services:
  lb:
    image: nsdavidson/haproxy
    command: --peer app --bind backend:rust-hello-world.default
    links:
      - app
    environment:
      HAB_HAPROXY: bind="*:8080"
    ports:
      - "8080:8080"
    depends_on:
      - app
  app:
    image: nsdavidson/hab
    command: hab start nsdavidson/rust-hello-world --peer redis --bind redis:redis.default --strategy at-once --url http://depot.nsdavidson.com/v1/depot
    depends_on:
      - redis
    links:
      - redis
  redis:
    image: nsdavidson/redis:latest
