version: "2"
services:
  lb:
    image: nsdavidson/haproxy
    command: --peer app --bind backend:rust-hello-world.app.default
    links:
      - app
    environment:
      HAB_HAPROXY: bind="*:8080"
    ports:
      - "8080:8080"
    volumes:
      - $DOCKER_CERT_PATH:$DOCKER_CERT_PATH
    depends_on:
      - app
  app:
    image: nsdavidson/rust-hello-world
    command: --peer redis --bind redis:redis.default --group app.default
    environment:
      - EXCLUDE_PORTS=9631
    depends_on:
      - redis
    links:
      - redis
  redis:
    image: nsdavidson/redis:latest
