version: "2"
services:
  app:
    image: nsdavidson/rust-hello-world:latest
    ports:
      - "8080:8080"
    command: --peer redis --bind redis:redis.default
    depends_on:
      - redis
    links:
      - redis
  redis:
    image: nsdavidson/redis:latest
